
site_title: 'Fabian Irsara | Web Developer, Photographer, Traveller'
site_keywords: ''
site_description: ''

poster_height: 100
poster_animation: 'zoom'
poster_vignette: false
poster_gradient: false
