
site_title: 'Fabian Irsara | Web Developer, Photographer, Traveller'
site_keywords: ''
site_description: ''

poster_height: 100
poster_scale: 0.5
poster_parallax: 0
poster_move: 1
poster_blur: 1
poster_fixed: true
poster_fade: 1
poster_image_opacity: 1
poster_vignette: false
poster_gradient: false
